# Generated by Django 3.1.2 on 2020-10-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(default='test', max_length=250),
        ),
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/images'),
        ),
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.CharField(default='title test', max_length=100),
        ),
    ]
